SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 900
PLAYER_BULLET_X_OFFSETS = [-15, 15]
PLAYER_BULLET_Y = 15
FRAME_TIME_PLAYER_MS = 20  # TODO change this later
FRAME_TIME_BULLETS_MS = 15  # TODO change this later
FRAME_TIME_ENEMY_MS = 300
ENEMY_SPEED = 1  # pix/frame
ENEMY_BULLET_X_OFFSETS = [150, 80]  # TODO no idea what is this used for but we are gonna use it later
PLAYER_SPEED = 10
BULLET_FRAMES = 180  # Whole screen, was 60 only for faster check up
BULLET_SPEED = 10  # pix/frame
